version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t python/lib/python3.11/site-packages/
  build:
    commands:
      - zip -r layer.zip python

artifacts:
  files:
    - layer.zip
  discard-paths: yes